name: job_assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.116.1
    - uvicorn==0.35.0
    - pydantic==2.11.7
    - pydantic-settings==2.10.1
    - python-dotenv==1.1.1
    - python-multipart==0.0.20
    - langchain==0.3.27
    - langchain-community==0.3.27
    - langchain-core==0.3.74
    - langchain-huggingface==0.3.1
    - langchain-perplexity==0.1.2
    - langchain-text-splitters==0.3.9
    - langsmith==0.4.14
    - openai==1.99.9
    - huggingface_hub==0.34.4
    - transformers==4.55.1
    - sentence-transformers==5.1.0
    - torch==2.7.1
    - torchaudio==2.7.1
    - torchvision==0.22.1
    - datasets==3.6.0
    - faiss-gpu-cu11==1.9.0
    - pinecone-client==6.0.0
    - redis==6.4.0
    - SQLAlchemy==2.0.43
    - psycopg2-binary==2.9.9
    - alembic==1.13.1
    - passlib[bcrypt]==1.7.4
    - python-jose[cryptography]==3.3.0
    - email-validator==2.2.0
    - PyMuPDF==1.26.3
    - pandas==2.3.1
    - numpy==1.26.4
    - scikit-learn==1.7.1
    - scipy==1.16.1
    - requests==2.32.4
    - httpx==0.28.1
    - aiohttp==3.10.11
    - jinja2==3.1.6
    - pyyaml==6.0.2
    - tqdm==4.67.1
    - tenacity==9.1.2
    - filelock==3.18.0
    - fsspec==2025.3.0
    - safetensors==0.6.2
    - tokenizers==0.21.4
    - regex==2025.7.34
    - packaging==25.0
    - typing-extensions==4.14.1
    - dataclasses-json==0.6.7
    - marshmallow==3.26.1
    - click==8.2.1
    - colorama==0.4.6
    - distro==1.9.0
    - greenlet==3.2.4
    - h11==0.16.0
    - h2==4.2.0
    - hf-xet==1.1.7
    - hpack==4.1.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx-sse==0.4.1
    - hyperframe==6.1.0
    - idna==3.10
    - jiter==0.10.0
    - joblib==1.5.1
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - markupSafe==3.0.2
    - mpmath==1.3.0
    - multidict==6.6.3
    - multiprocess==0.70.16
    - mypy_extensions==1.1.0
    - networkx==3.5
    - optree==0.17.0
    - orjson==3.11.2
    - pillow==11.3.0
    - pinecone-plugin-interface==0.0.7
    - propcache==0.3.1
    - pyarrow==21.0.0
    - pybind11==3.0.0
    - pybind11-global==3.0.0
    - pycparser==2.22
    - pydantic_core==2.33.2
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - redis==6.4.0
    - setuptools==80.9.0
    - six==1.17.0
    - sniffio==1.3.1
    - starlette==0.47.2
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - torchvision-extra-decoders==0.0.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - uvloop==0.21.0
    - watchfiles==1.1.0
    - websockets==15.0.1
    - wheel==0.45.1
    - xxhash==3.5.0
    - yarl==1.20.1
    - zstandard==0.23.0
    - aiohappyeyeballs==2.4.4
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.10.0
    - async-timeout==5.0.1
    - attrs==25.3.0
    - brotli==1.1.0
    - certifi==2025.8.3
    - cffi==1.17.1
    - charset-normalizer==3.4.3
    - dill==0.3.8
    - frozenlist==1.7.0
    - gmpy2==2.2.1
    - hf-xet==1.1.7
    - hpack==4.1.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - httpx-sse==0.4.1
    - hyperframe==6.1.0
    - idna==3.10
    - jiter==0.10.0
    - joblib==1.5.1
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - markupSafe==3.0.2
    - mpmath==1.3.0
    - multidict==6.6.3
    - multiprocess==0.70.16
    - mypy_extensions==1.1.0
    - networkx==3.5
    - optree==0.17.0
    - orjson==3.11.2
    - pillow==11.3.0
    - pinecone-plugin-interface==0.0.7
    - propcache==0.3.1
    - pyarrow==21.0.0
    - pybind11==3.0.0
    - pybind11-global==3.0.0
    - pycparser==2.22
    - pydantic_core==2.33.2
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - setuptools==80.9.0
    - six==1.17.0
    - sniffio==1.3.1
    - starlette==0.47.2
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - torchvision-extra-decoders==0.0.2
    - tzdata==2025.2
    - urllib3==2.5.0
    - uvloop==0.21.0
    - watchfiles==1.1.0
    - websockets==15.0.1
    - wheel==0.45.1
    - xxhash==3.5.0
    - yarl==1.20.1
    - zstandard==0.23.0
